### ISSUE TITLE
Setting transform to NULL or something else doesn't update the legend

### ISSUE THREAD

**Issue by raivivek** [stemangiola/tidyHeatmap#10]
Hi,

Looks like in my usage, the legend does not update if I change the `transform` to something else (log) or turn it off by setting to `NULL`. I tested with the example in README with `transform = NULL`.

Also, thanks for the awesome package. It is going to very useful. I will be happy to contribute if that helps.

**Comment by stemangiola** [comment]
Hello, for clarity could you paste the reproducible code with screenshot of the plot indicating what you mean exactly?

**Comment by stemangiola** [comment]
It is a bit awkward time. I have changed idea on how to organise tranform and scale. Now they are independent.

Please try again.

**Comment by raivivek** [comment]
Thanks! I am able to turn off scaling with `.scale='none'` and that does update the legend. Just a quick question -- how do I use the default blue-red colorscheme that comes with ComplexHeatmap?

**Comment by stemangiola** [comment]
No worries.

try palette_value = c("red", "white", "blue")

For more flexibility read the README.
