### ISSUE TITLE
handling RangedSummarizedExperiment (tximeta -> tidybulk procedure)

### ISSUE THREAD

**Issue by AMChalkie** [stemangiola/tidyHeatmap#100]
Hi Stefano,

You probably saw this request coming :)

Best wishes

counts_scaled_tx %>% 

  # filter lowly abundant
  keep_abundant() %>%

    # extract 500 most variable genes
    keep_variable( .abundance = counts_scaled, top = 500) %>%

    # create heatmap
    tidyHeatmap::heatmap(
          .column = sample,
          .row = feature,
          .value = counts_scaled,
          transform = log1p
      )

No group or design set. Assuming all samples belong to one group.
Getting the 500 most variable genes
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'heatmap' for signature '"RangedSummarizedExperiment"'

4: stop(gettextf("unable to find an inherited method for function %s for signature %s", 
       sQuote(fdef@generic), sQuote(cnames)), domain = NA)
3: (function (classes, fdef, mtable) 
   {
       methods <- .findInheritedMethods(classes, fdef, mtable)
       if (length(methods) == 1L) 
           return(methods[[1L]])
       else if (length(methods) == 0L) {
           cnames <- paste0("\"", vapply(classes, as.character, 
               ""), "\"", collapse = ", ")
           stop(gettextf("unable to find an inherited method for function %s for signature %s", 
               sQuote(fdef@generic), sQuote(cnames)), domain = NA)
       }
       else stop("Internal error in finding inherited methods; didn't return a unique method", 
           domain = NA)
   })(list(structure("RangedSummarizedExperiment", package = "SummarizedExperiment")), 
       new("standardGeneric", .Data = function (.data, .row, .column, 
           .value, transform = NULL, scale = "none", palette_value = c("#440154FF", 
               "#21908CFF", "#fefada"), palette_grouping = list(), 
           .scale = NULL, ...) 
       standardGeneric("heatmap"), generic = structure("heatmap", package = "tidyHeatmap"), 
           package = "tidyHeatmap", group = list(), valueClass = character(0), 
           signature = c(".data", ".row", ".column", ".value", "transform", 
           "scale", "palette_value", "palette_grouping", ".scale"
           ), default = NULL, skeleton = (function (.data, .row, 
               .column, .value, transform = NULL, scale = "none", 
               palette_value = c("#440154FF", "#21908CFF", "#fefada"), 
               palette_grouping = list(), .scale = NULL, ...) 
           stop(gettextf("invalid call in method dispatch to '%s' (no default method)", 
               "heatmap"), domain = NA))(.data, .row, .column, .value, 
               transform, scale, palette_value, palette_grouping, 
               .scale, ...)), <environment>)
2: tidyHeatmap::heatmap(., .column = sample, .row = feature, .value = counts_scaled, 
       transform = log1p)
1: counts_scaled_tx %>% keep_abundant() %>% keep_variable(.abundance = counts_scaled, 
       top = 500) %>% tidyHeatmap::heatmap(.column = sample, .row = feature, 
       .value = counts_scaled, transform = log1p)

**Comment by stemangiola** [comment]
> You probably saw this request coming :)

I thought about this many times, however for the moment I am of the idea of keeping the `tidybulk`, `tidySE`, `tidyHeatmap` independent.

The solution is

```r
counts_scaled_tx %>% 

  # filter lowly abundant
  keep_abundant() %>%

    # extract 500 most variable genes
    keep_variable( .abundance = counts_scaled, top = 500) %>%

    # convert to tibble
    as_tibble() %>%

    # create heatmap
    tidyHeatmap::heatmap(
          .column = sample,
          .row = feature,
          .value = counts_scaled,
          transform = log1p
      )
```

**Comment by AMChalkie** [comment]
Thanks.

**Comment by AMChalkie** [comment]
Spoke too soon...

I had to add this line to get it to work properly:

 # convert to tibble
    as_tibble() %>% mutate(feature=.feature) %>%  mutate(sample=sample_name) %>%


counts_scaled_tx %>% 
+     
+     # filter lowly abundant
+     keep_abundant() %>%
+     
+     # extract 500 most variable genes
+     keep_variable( .abundance = counts_scaled, top = 500) %>%
+     
+     # convert to tibble
+     as_tibble() %>% 
+     
+     # create heatmap
+     tidyHeatmap::heatmap(
+         .column = sample,
+         .row = feature,
+         .value = counts_scaled,
+         annotation = c(names, condition),
+         scale = "row", # "column" or "both"
+         transform = log1p
+     )
No group or design set. Assuming all samples belong to one group.
Getting the 500 most variable genes
Error in validation.tbl_df(., !!.column, !!.row, !!.value) : 
  tidyHeatmap says: One or more columns sample, feature or counts_scaled are missing from your data frame.
> 
> counts_scaled_tx %>% 
+     
+     # filter lowly abundant
+     keep_abundant() %>%
+     
+     # extract 500 most variable genes
+     keep_variable( .abundance = counts_scaled, top = 500) %>%
+     
+     # convert to tibble
+     as_tibble()
No group or design set. Assuming all samples belong to one group.
Getting the 500 most variable genes
# A tibble: 7,500 × 24
   .feature .sample counts abundance length counts_scaled sample_name condition fq1   fq2   salmon_command names files_orig   TMM multiplier  tx_id gene_id tx_name .abundant seqnames
   <chr>    <chr>    <dbl>     <dbl>  <dbl>         <dbl> <chr>       <chr>     <chr> <chr> <chr>          <chr> <chr>      <dbl>      <dbl>  <int> <list>  <chr>   <lgl>     <fct>   
 1 ENSMUST… JY1a      372       6.37 1773.           691. JY1a        unknown   /mnt… /mnt… salmon quant … JY1a  data/salm…  1.07       1.86 122370 <chr>   ENSMUS… TRUE      chr17

**Comment by stemangiola** [comment]
`heatmap` takes the column, names. That of course should be present in your tibble. Have a look to the tidfyHeatmap README.

Try the below

```r


+     tidyHeatmap::heatmap(
+         .column = .sample,
+         .row = .feature,
+         .value = counts_scaled,
+         scale = "row", # "column" or "both"
+         transform = log1p
+     )

```
