### ISSUE TITLE
main = "title", doesn't work?

### ISSUE THREAD

**Issue by HijaziHassan** [stemangiola/tidyHeatmap#104]
What is the syntax to add a title to the heatmap using the `tidyHeatmap` package?

Thank you?

**Comment by stemangiola** [comment]
Can you give me an example of where yo have seen this? With a weblink reference?

Thanks.

**Comment by mattgalbraith** [comment]
See https://github.com/stemangiola/tidyHeatmap/issues/69

**Comment by stemangiola** [comment]
@HijaziHassan was @mattgalbraith helpful?

Can we close? @HijaziHassan or @mattgalbraith, if you were up for it, we could add that example to the README.Rmd

**Comment by mattgalbraith** [comment]
You can use the `column_title` argument from `ComplexHeatmap::Heatmap()` to add a title, however it will overwrite the existing column title.

Following the example from the README:
```
mtcars_tidy |>
    heatmap(
          `Car name`, Property, Value, 
          scale = "row", 
          column_title = "TITLE"
           ) |>
    annotation_tile(hp)
```
![hm4](https://user-images.githubusercontent.com/46791232/207779112-e5617d07-2cde-459b-8b08-c134825ed939.png)

**Comment by stemangiola** [comment]
Great solution. I'm wondering if ComplexHeatmap has a `title` per-se.

**Comment by mattgalbraith** [comment]
> Great solution. I'm wondering if ComplexHeatmap has a `title` per-se.

I cannot find one for single heatmaps
https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html?q=title#heatmap-titles

However, using the `ComplexHeatmap::draw()` to combine multiple heatmaps does allow for and additional `column_title`
https://jokergoo.github.io/ComplexHeatmap-reference/book/a-list-of-heatmaps.html?q=title#heatmap-list-titles

**Comment by stemangiola** [comment]
> However, using the `ComplexHeatmap::draw()` function to combine multiple heatmaps does allow for an additional `column_title`

Well spotted. In this case the less hacky solution is

```r

heatmap(...) |>
as_ComplexHeatmap() |>
draw(
  column_title = "Three heatmaps, column title", 
  column_title_gp = gpar(fontsize = 16)
)

```

**Comment by stemangiola** [comment]
We could even add this solution in the README

**Comment by mattgalbraith** [comment]
> Well spotted. In this case the less hacky solution is
> 
> ```r
> mtcars_tidy |> 
>     heatmap(`Car name`, Property, Value,    scale = "row"   ) |>
>     as_ComplexHeatmap() |>
>     draw(
>         column_title = "Three heatmaps, column title", 
>         column_title_gp = gpar(fontsize = 16)
>     )
> ```
Possibly not a big deal for most, but unfortunately this does not work with `wrap_heatmap()` which allows heatmaps to be assembled with `patchwork` and/or saved with `ggsave()`


> We could even add this solution in the README under `External ComplexHeatmap functionalities` 

I may have some other suggestions for that section but perhaps off-topic here

**Comment by stemangiola** [comment]
> this does not work with `wrap_heatmap()`

With patchwork/ggplot it's even cleaner.

```r

wrap_heatmap(...) + ggtitle("TITLE")

```

we could propose this or both solution instead
