### ISSUE TITLE
Feature request - layer_symbol()

### ISSUE THREAD

**Issue by mattgalbraith** [stemangiola/tidyHeatmap#105]
Firstly, thank you for all the effort put into this super-useful package. I do have a couple of minor feature requests that would help with generating publication-quality heatmaps with minimal additional editing required.

**1) I would like to be able to specify the (relative) size of the character plotted by the layer_symbol() and related layer_*() functions (for example when using this to indicate significance), as the results are somewhat unpredictable and can be unweildy depending on the exported size of the resulting heatmaps.**

Following the example given in the README:
```
mtcars_tidy |>
    mutate(pval = if_else(abs(Value) > 0.7, 0.001, 1)) |>  # Add toy p-values
    heatmap(`Car name`, Property, Value,    scale = "row"   ) |>
    annotation_tile(hp) |> 
    layer_point(pval < 0.05)
```
Small export
![hm1](https://user-images.githubusercontent.com/46791232/207454374-9c449c2f-4343-42d5-bf07-ad80d777d5af.png)

Larger export
![hm2](https://user-images.githubusercontent.com/46791232/207454354-2f02ee00-0997-4a87-a439-4ae679faba7a.png)

**2) It would also be very nice to have the ability to specify a wider range of symbols or characters using the layer_symbol() function.** 

I was able to add the "star" symbol (pch = 8) by modifying the layer_symbol() function, but an asterisk (5-sided) is more commonly used in my field, but I could not see how to control the size:
```
layer_symbol2 <- function (.data, ..., symbol = "point") 
{
  .data_drame = .data@data
  symbol_dictionary = list(point = 21, square = 22, diamond = 23, 
                           arrow_up = 24, arrow_down = 25, star = 8)
  if (!symbol %in% names(symbol_dictionary) | length(symbol) != 
      1) 
    stop(sprintf("tidyHeatmap says: the symbol argument must be one character string, among %s", 
                 paste(names(symbol_dictionary))))
  . = NULL
  column = NULL
  row = NULL
  .horizontal = .data@arguments$.horizontal
  .vertical = .data@arguments$.vertical
  .abundance = .data@arguments$.abundance
  .data@layer_symbol = .data@layer_symbol %>% bind_rows(.data_drame %>% 
                                                          droplevels() %>% mutate(column = !!.horizontal %>% as.factor %>% 
                                                                                    as.integer, row = !!.vertical %>% as.factor %>% as.integer) %>% 
                                                          filter(...) %>% select(column, row) %>% mutate(shape = symbol_dictionary[[symbol]]))
  .data
}
```

```
mtcars_tidy |>
    mutate(pval = if_else(abs(Value) > 0.7, 0.001, 1)) |>  # Add toy p-values
    heatmap(`Car name`, Property, Value,    scale = "row"   ) |>
    annotation_tile(hp) |> 
    layer_symbol2(pval < 0.05, symbol = "star")
```

Heatmap with stars:
![hm3](https://user-images.githubusercontent.com/46791232/207461808-98f1158c-13da-465f-a4ba-a23084198aa2.png)

**Comment by stemangiola** [comment]
Thanks for the proactive issue. You are very close to contributing to tidyHeatmap with a pull request and having your name in the repo! ;)

I am quite overwhelmed at the moment, but I can surely support you. 

All symbols available are obviously what `ComplexHeatmap` provides (as that is our "graphic engine"). 
- Is your symbol provided by `ComplexHeatmap` package?
- How `ComplexHeatmap` handles the symbol size?

**Comment by mattgalbraith** [comment]
I will have to hunt down some older code I have for this same task with `ComplexHeatmap` (I mostly stopped using this package directly after discovering `tidyHeatmap`), and I will see if I can work out how symbol and size are handled.

**Comment by stemangiola** [comment]
If I understand you have 2 problems,

- you cannot find 5-star symbol in tidyHeatmap or ComplexHeatmap
- tidyHeatmap cannot specify size, which I agree is important. This smells like something easy to implement once we understand where Complexheatmap specifies this aesthetics.

**Comment by mattgalbraith** [comment]
Correct, it would be great to have control over both symbol/character and (relative) size.

I will share some of my example code when I get more time, but for now, here is the relevant section of the `ComplexHeatmap` documentation: https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#customize-the-heatmap-body

Happy to help contribute code / test any potential solutions.

**Comment by mattgalbraith** [comment]
@stemangiola 
Here is an example of how to conditionally display an asterisk using the `cell_fun` argument of the `ComplexHeatmap::Heatmap` function. Much more complicated (and still imperfect) than the `tidyHeatmap` `layer_symbol()` approach.
```
# set up data for heatmap
hm_dat <- mtcars_tidy |> 
  mutate(pval = if_else(abs(Value) > 0.7, 0.001, 1)) |>  # Add toy p-values
  select(`Car name`, Property, Value) |> 
  pivot_wider(names_from = Property, values_from = Value) |> 
  column_to_rownames(var = "Car name")

# set up p-values for heatmap
hm_pvals <- mtcars_tidy |> 
  mutate(pval = if_else(abs(Value) > 0.7, 0.001, 1)) |>  # Add toy p-values
  select(`Car name`, Property, pval) |> 
  pivot_wider(names_from = Property, values_from = pval) |> 
  column_to_rownames(var = "Car name")

# function to display asterisk when pval < 0.05
pval_fun <- function(j, i, x, y, width, height, fill) {
  if(hm_pvals[i, j] < 0.05)
    grid.text(
      "*", # asterisk but not very well centered
      x, y, gp = gpar(fontsize = 12))
}

# plot heatmap with ComplexHeatmap
ComplexHeatmap::Heatmap(
  hm_dat,
  cell_fun = pval_fun
)
```
![image](https://user-images.githubusercontent.com/46791232/207785187-b1d7bc03-ff1e-4959-a845-8812248efc0b.png)

Not sure if this helps much with potential modifications for `layer_symbol()`.  I will need to understand better how the InputHeatmap class is passed to / interpreted by `ComplexHeatmap`

**Comment by stemangiola** [comment]
> Here is an example of how to conditionally display an asterisk using the `cell_fun` argument

Scary.

In the backend I am currently using the `ComplexHeatmap` `layer_fun` with the function `grid.points`. Code below.

Interestingly you don't use `layer_fun` nor `grid.points`

```r

	# On-top layer
	tidyHeatmap@input$layer_fun = function(j, i, x, y, w, h, fill) {
		ind = 
			tibble(row = i, column = j) |>
			rowid_to_column("index_column_wise") |>
			
			# Filter just points to label
			inner_join(tidyHeatmap@layer_symbol, by = c("row", "column")) |>
			select(`index_column_wise`, `shape`)
		
		if(nrow(ind)>0)
			grid.points(
				x[ind$index_column_wise], y[ind$index_column_wise], 
				pch = ind$shape , 
				size = unit(3, "mm"), 
				gp = gpar(col = NULL, fill="#161616")
			)
	}

```

**Comment by stemangiola** [comment]
From a bigger perspective, I think that (i) size customisation is time better spent than (ii) symbol customisation, especially because very custom ASCII they are not rendering great as you have shown.

**Comment by mattgalbraith** [comment]
> From a bigger perspective, I think that (i) size customisation is time better spent than (ii) symbol customisation, especially because very custom ASCII they are not rendering great as you have shown.

Agreed, but it seems that (ii) was simpler than I realized - I had assumed that pch was limited to the standard 0-25 symbols that usually appear in a quick internet search, but it seems that more are available (see https://davidrroberts.wordpress.com/2015/06/02/r-pch-symbol-library-plot/).

```
layer_symbol2 <- function (.data, ..., symbol = "point") 
{
  .data_drame = .data@data
  symbol_dictionary = list(
    point = 21, 
    square = 22, 
    diamond = 23, 
    arrow_up = 24, 
    arrow_down = 25, 
    star = 8, 
    asterisk = 42
  )
  if (!symbol %in% names(symbol_dictionary) | length(symbol) != 
      1) 
    stop(sprintf("tidyHeatmap says: the symbol argument must be one character string, among %s", 
                 paste(names(symbol_dictionary))))
  . = NULL
  column = NULL
  row = NULL
  .horizontal = .data@arguments$.horizontal
  .vertical = .data@arguments$.vertical
  .abundance = .data@arguments$.abundance
  .data@layer_symbol = .data@layer_symbol |> 
    bind_rows(.data_drame |> 
                droplevels() |> 
                mutate(
                  column = !!.horizontal |> as.factor |> as.integer, 
                  row = !!.vertical |> as.factor |> as.integer
                ) |> 
                filter(...) |> 
                select(column, row) |> 
                mutate(shape = symbol_dictionary[[symbol]])
    )
  .data
}
```
![image](https://user-images.githubusercontent.com/46791232/207915283-de56abdb-ae41-4909-aefa-f051af6a5c83.png)

Regarding (i) size, I will try to find some time to look into this further - maybe using `npc` instead of `mm` as the size units would work?

**Comment by stemangiola** [comment]
Great! 

Do you want to create a pull request to add these two symbols to `layer_symbol` and create exposed `layer_star` and `layer_asterisk`?

**Comment by mattgalbraith** [comment]
Yes, will do when I get a chance.
