### ISSUE TITLE
Changing clustering and distance methods

### ISSUE THREAD

**Issue by singjc** [stemangiola/tidyHeatmap#119]
Hello,

Is it possible to change the distance and clustering methods?

In ComplexHeatmap you can change these methods using:

```
Heatmap(mat, name = "mat", 
clustering_distance_cols = function(m) vegdist(m, method="jaccard"),
clustering_method = "ward.D2")
```

When I try do the same using tidyHeatmap 

```
data_long |> 
  heatmap(gene, sample, log2_intensity,
          scale = "both",
          rect_gp = grid::gpar(col = "#161616", lwd = 0.5),
          palette_value = circlize::colorRamp2(
            seq(2, -2, length.out = 11), 
            RColorBrewer::brewer.pal(11, "RdBu")
        ),
        clustering_distance_cols = function(m) vegdist(m, method="jaccard"),
        clustering_method = "ward.D2") |>
  split_rows(3) |>
  split_columns(2)
```

I get this error

> Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'show': argument 10 matches multiple formal arguments
  
  Is it not possible to change the distance and clustering method in tidyHeatmap?
  
  Best,
  
  Justin

**Comment by stemangiola** [comment]
In this branch, I have added an example of alternative distance and methods that are passed to ComplexHeatmap

https://github.com/stemangiola/tidyHeatmap/tree/distance-methods

Have a look if that helps.

**Comment by singjc** [comment]
Great, thanks that helps! Got it working now.
