### ISSUE TITLE
Error when heatmap is sparse

### ISSUE THREAD

**Issue by raivivek** [stemangiola/tidyHeatmap#40]
Hi,

I have some data in long format: Gene, Model, Value. I am trying to plot the heatmap using tidyHeatmap but I get the following error:

```
Error in seq.default(from = min(abundance_mat), to = max(abundance_mat),  : 
  'from' must be a finite number
```

There are no Na/NULL/Inf values in the dataset, but the matrix is sparse. That is, not all models have a value of the gene so plotting it in Heatmap format should have a lot of empty cells.

Reproducible example

```
> tmp <- data.frame(G = c('G1', 'G2', 'G3'), Y = c('M1', 'M1', 'M2'), V = c(1,2,3))
> as_tibble(tmp)
# A tibble: 3 x 3
  G     Y         V
  <chr> <chr> <dbl>
1 G1    M1        1
2 G2    M1        2
3 G3    M2        3
> as_tibble(tmp) %>% tidyHeatmap::heatmap(G, Y, V)
Error in seq.default(from = min(abundance_mat), to = max(abundance_mat),  : 
  'from' must be a finite number
```

Any thoughts?

**Comment by stemangiola** [comment]
Hello @raivivek ,

yes I have an idea. Do you think is possible to send your anonymized data? This would be the best way to really test you issue, without going back and forth.

mangiola.s@wehi.edu.au

**Comment by stemangiola** [comment]
Thanks @raivivek for the message.

I have solved things on my side. Now your minimal example fails on hclust of ComplexHeatmap. Basically your minimal example is too minimal.

Please install this branch

https://github.com/stemangiola/tidyHeatmap/tree/fix-sd-unique

and run it with a less minimal example. Let me know how you go.

**Comment by raivivek** [comment]
Thanks! That appears to work for me as well -- fails on clustering step which makes sense. So, you can close this issue. I noticed one error when trying to use `tidyHeatmap` without importing it (tidyHeatmap::heatmap for example) just now -- 
```
Error in as.vector(y) : object 'type_to_annot_function' not found
```

However, the same line works fine after importing tidyHeatmap. I believe in the correct case, it should work either way. Thanks for the quick response!

**Comment by stemangiola** [comment]
Hello @raivivek ,

could you please install 

https://github.com/stemangiola/tidyHeatmap/tree/move-type_to_annot_function

and check that that error disappeared?

**Comment by stemangiola** [comment]
Hello @raivivek I'm not sure what thumps up mean in this case. :) If you test and came out OK please close the issue.

**Comment by raivivek** [comment]
Hi @stemangiola -- I haven't gotten around to checking the new fix, but appreciate the quick response and will check it soon (maybe tomorrow). Hence, the thumbs up. :)
