### ISSUE TITLE
Adding heatmaps

### ISSUE THREAD

**Issue by deborah-chasman** [stemangiola/tidyHeatmap#55]
Hello,
I've been enjoying using tidyHeatmap and have made some lovely heatmaps! 
I noticed that one change between the CRAN version and this version is that we can no longer add heatmaps together like we can using ComplexHeatmap. Is there a new way to do this?

Here is an example:

![Untitled-1](https://user-images.githubusercontent.com/9661893/90926352-91555e00-e3b8-11ea-9809-330546bfbed6.png)

I think I can create the purple/white heatmap by calling "add_tile" once per column as a work-around. 

If this feature isn't in the new version, I hope you'll consider adding it in the future. Thank you!

**Comment by deborah-chasman** [comment]
Hello,

Thank you very much for your quick response! It looks like the first thing I was missing was that I needed to call "show" to make them into ComplexHeatmaps.

However, I'm running into problems with both of my options for making the plot I showed above: (1) adding tile annotations and then removing the legends, or (2) trying to add ComplexHeatmaps that were generated by tidyHeatmap.

I think my problem with (1) is that it's not clear how to remove the annotation legend in ComplexHeatmap if you aren't explicitly adding a HeatmapAnnotation object. I am able to pass show_heatmap_legend=F to tidyHeatmap::heatmap() and turn off the heatmap legend, but I'm not able to find a matching argument for turning off annotation legends. The show_legend=F param only works (as far as I can tell) when you are constructing an annotation. I think I would need to ask the ComplexHeatmap folks about removing legends after the fact from a ComplexHeatmap.

For (2), it seems that I can make the ComplexHeatmaps fine with show() (thanks!), but I get an error when I try to plot them together. ComplexHeatmap overrides the "+" operator for combining heatmaps. 

I put together a minimal example:

```
m <- matrix(rnorm(10*10), 10, 10) 
rownames(m) <- sprintf("g%d", 1:10)
colnames(m) <- sprintf("s%d", 1:10)
expr <- m %>% as_tibble(rownames="gene") %>%
    gather(sample, value, -gene)

m2 <- matrix(rnorm(10*10), 10, 10) 
rownames(m2) <- sprintf("g%d", 1:10)
colnames(m2) <- sprintf("s%d", 1:10)
expr2 <- m2 %>% as_tibble(rownames="gene") %>%
    gather(sample, value2, -gene)

hm <- expr %>% 
    heatmap(gene, sample, value)
hm2 <- expr2 %>% 
    heatmap(gene, sample, value2)
```

Now I try adding them together:
```
mylist <- (show(hm) + show(hm2))
```

We can see that the ht_list was created successfully:

```
mylist@ht_list
$value

$value2
```

Now try to plot the list:
```
mylist
Error: index out of bounds ("unit" subsetting)
```

It seems that there is something about the way the two ComplexHeatmaps were constructed that ComplexHeatmap doesn't want to draw them together.

If this is getting too far out of the scope of tidyHeatmap and not something you have the time or interest to pursue, I completely understand! 
Thank you for your time so far!

**Comment by stemangiola** [comment]
1) I tried couple of hours to set up a argument passing/legend omission for specific labels. However ComplexHeatmap makes it hard to manage specific legend omission to start with. So no luck there at the moment.

2) for this option thi may help 
```
x = tidyHeatmap::heatmap(
tidyHeatmap::pasilla,
.column = sample,
.row = symbol,
.value = `count normalised adjusted`,
) %>%
add_tile(condition) %>% show()
```
```
x %>% class

[1] "HeatmapList"
attr(,"package")
[1] "ComplexHeatmap"
```
Can you merge HeatmapLists?

**Comment by deborah-chasman** [comment]
Hi,

1. Sorry to hear you spent so much time trying to get this to work!

2. Yes, I can merge HeatmapLists just fine, and if I access each list item I can draw it. It looks like the problem arises when I try to show/draw the list as a composite heatmap. The error message is similar to what's reported here: https://github.com/jokergoo/ComplexHeatmap/issues/56 I wonder if it might be a good time for me to take the question there.

Thank you again.

**Comment by stemangiola** [comment]
Hello,

how did you solve the problem at the end?

**Comment by deborah-chasman** [comment]
Thanks for following up! To be honest, I ended up solving it with a non-solution. When I want to combine heatmaps, I use either the old version of tidyHeatmap or ComplexHeatmap. I still use the newer tidyHeatmap regularly, though.

**Comment by stemangiola** [comment]
Uhh that's sad.

I have spent couple of hours trying. The problem is the inconsistent behaviour of the show method

See https://rpubs.com/stemangiola/754096

I have asked help in the CRAN mailing list. I'm confident I will manage to solve it

**Comment by stemangiola** [comment]
I have asked here https://community.rstudio.com/t/quite-a-mystery-show-method-giving-inconsistent-outcomes-when-triggered-indirectly-or-directly/102443

**Comment by deborah-chasman** [comment]
Thanks so much for working on this!

**Comment by stemangiola** [comment]
I might have found a solution to use patchwork with tidyHeatmap
```r
grob<-grid::grid.grabExpr(ComplexHeatmap::draw(ComplexHeatmap::draw(show(plot_heatmap))))
library(patchwork)

# Return plot
wrap_elements(grob) + ...	
```
Can you please try if it is a possible solution for you. I will try to implement it. This gives the possibility to integrate it with ggplot too.

**Comment by stemangiola** [comment]
> Now I try adding them together:
> 
> ```
> mylist <- (show(hm) + show(hm2))
> ```

This was also solved in 

You can now use `as_ComplexHeatmap` for less standard ComplexHeatmap functionalities.
```r
as_ComplexHeatmap(hm) + as_ComplexHeatmap(hm2)
```
