### ISSUE TITLE
Custom colours for groups

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidyHeatmap#56]
Keep track of this [from here](https://github.com/stemangiola/tidySCE/pull/2#issuecomment-686943611), don't seem to be able to specify colours for the groups.

With below, the colours don't change. 

pbmc_small_cluster %>%
  join_transcripts(transcripts = marker_genes) %>% 
  group_by(label) %>% 
  heatmap(transcript, cell, abundance_counts, .scale = "column", 
                 palette_grouping = list(c("blue", "orange", "green", "yellow")))

**Comment by mblue9** [comment]
FYI I tested this & it works with the current master version, just not the CRAN release, maybe you fixed it here? : https://github.com/stemangiola/tidyHeatmap/commit/aba46d673f9137d6967457ff2fb43ade7e21d473
If it's possible to make a new CRAN release I can make the colourblind-friendly in the tidySCE vignette.

**Comment by stemangiola** [comment]
Sure, I will submit one of these days!
