### ISSUE TITLE
Oncoprint style heat map

### ISSUE THREAD

**Issue by alhafidzhamdan** [stemangiola/tidyHeatmap#57]
Hi there,
Thanks very much for creating this package! 
I wonder if there’s a plan to include oncoprint like heatmap function? 
like plotting dots (binary, factors) as data ie mutations.
Thanks.

**Comment by stemangiola** [comment]
Oncoprint is really extensive. Could you please give a visual example of the most common use of oncoprint visualisations?

**Comment by alhafidzhamdan** [comment]
Just taken directly from complexheatmap - https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html

**Comment by stemangiola** [comment]
Hello,

sorry for the silence. Did you find a solution?

**Comment by caravagn** [comment]
I think the `memoSort ` function [here](https://gist.github.com/armish/564a65ab874a770e2c26) here could be used, disabling row/cols clustering.

**Comment by stemangiola** [comment]
I don't have the throughput to take care of this. If anyone wants to contribute is very welcome. I close for the time being.
