### ISSUE TITLE
Further arguments to be passed to ComplexHeatmap::Heatmap

### ISSUE THREAD

**Issue by lixiang117423** [stemangiola/tidyHeatmap#58]
Hello Sir,
I am learning your package to construct a heatmap.
I am trying to pass `row_title` to `heatmap`, but it can not work correctly.

what do I do?
Any reply appreciated!

The code as follows:

`pasilla_plus <- 
  tidyHeatmap::pasilla %>%
  dplyr::mutate(act = activation) %>% 
  tidyr::nest(data = -sample) %>% #创建list
  dplyr::mutate(size = rnorm(n(), 4,0.5)) %>%
  dplyr::mutate(age = runif(n(), 50, 200)) %>%
  tidyr::unnest(data) 

pasilla_plus %>%
  heatmap(
    .column = sample,
    .row = symbol,
    .value = `count normalised adjusted`,
    row_title = 'test title'
  )
`

**Comment by stemangiola** [comment]
Hello,

```
pasilla_plus <- 
    tidyHeatmap::pasilla %>%
    dplyr::mutate(act = activation) %>% 
    tidyr::nest(data = -sample) %>%
    dplyr::mutate(size = rnorm(n(), 4,0.5)) %>%
    dplyr::mutate(age = runif(n(), 50, 200)) %>%
    tidyr::unnest(data) 

# Plot
pasilla_plus %>%
    rename(`test title` = sample) %>%
    heatmap(
        .column = `test title`,
        .row = symbol,
        .value = `count normalised adjusted`
    ) 
```
