### ISSUE TITLE
Stop heatmap from clustering columns

### ISSUE THREAD

**Issue by angelolimeta** [stemangiola/tidyHeatmap#59]
Hi @stemangiola !
First of all, i just wanted to say that this is a very nice and useful package! I'm just wondering if there's any way to not cluster the columns?

Best,
Angelo

**Comment by stemangiola** [comment]
Thanks!

tidyHeatmap ses ComplexHeatmaps in the backend. If you find the command to not cluster the columns and give it to the heatmap function it should work.

Let me know

**Comment by raivivek** [comment]
Just for completeness, the way to do it is to pass `cluster_rows = FALSE` or `cluster_columns = FALSE` as additional arguments to tidyHeatmap.

**Comment by stemangiola** [comment]
Thanks!
