### ISSUE TITLE
Error message doesn't correspond to help; error running tidyHeatmap

### ISSUE THREAD

**Issue by raivivek** [stemangiola/tidyHeatmap#61]
Hi,

I'm using the latest version (`devtools`) of tidyHeatmap for a visualization task. I'm running into an error that doesn't seem to correspond with what is available in the help. Please see below.
```
df %>% tidyHeatmap::heatmap(., .row = gene, .column = sample, .value = log2FoldChange)
Error in validation.tbl_df(., !!.column, !!.row, !!.value) : tidyHeatmap says: One or more columns .sample .transcript or .abundance are missing from your data frame.
```

However, there's no .gene or .abundance in the help; and I am unable to tell why this function is failing.

**Comment by stemangiola** [comment]
Hello,

thanks for the note. I have fixed the issue in the master branch, please reinstall from github.

**Comment by raivivek** [comment]
Thanks for the quick response. Latest master fixes the issue for me.
