### ISSUE TITLE
Unable to use tidyHeatmap::heatmap() function with "tidybulk" object

### ISSUE THREAD

**Issue by jeremiah-holt** [stemangiola/tidyHeatmap#66]
Hi, I was following this nice guide provided by you or a colleague here: https://stemangiola.github.io/bioc_2020_tidytranscriptomics/articles/tidytranscriptomics.html

I am at the hierarchical clustering/heatmap step, but whenever I try to run the tidyHeatmap::heatmap function I get an internal error for the tidybulk object saying that it cannot find a function for class "tidybulk".

My code for making the tidybulk object from a tidy_df and then passing it for filtering and clustering/plotting:

"tt %>% 
  tidybulk(.sample=samples, .transcript=transcript, .abundance=abundance) %>%  
  keep_variable(.abundance = abundance, top = 500) %>%
  tidyHeatmap::heatmap(.row = transcript, #tidyHeatmap 
          .column = samples,
          .value = abundance)
"

But then I get the following error message:
"> tt %>% 
+   tidybulk(.sample=samples, .transcript=transcript, .abundance=abundance) %>%  
+   keep_variable(.abundance = abundance, top = 500) %>%
+   tidyHeatmap::heatmap(.row = transcript, #tidyHeatmap 
+           .column = samples,
+           .value = abundance)
Getting the 500 most variable genes
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘heatmap’ for signature ‘"tidybulk"’
"

Am I doing something wrong here?

Thanks,

J

**Comment by stemangiola** [comment]
Hello, nothing wrong. Just that that workshop is executed with an old version of tidyHeatmap.

Now like in https://github.com/stemangiola/bioc2021_tidytranscriptomics we suggest the use of 

SummarizedExperiment
tidySummarizedExperiment
and do (until tidyHeatmap won't be integrated in tidybulk) 

object %>% as_tibble() %>% heatmap()

**Comment by jeremiah-holt** [comment]
Thanks so much for the helpful reply. Looks like the as_tibble() function does the trick.
