### ISSUE TITLE
how to make the lower limit of the “value” scale to be “0” 

### ISSUE THREAD

**Issue by bishimonster** [stemangiola/tidyHeatmap#68]
As for your heatmap presented here, the lower limit is -2, I wanna adjust it to 0 with some scaled methods, do you have any good idea.

**Comment by stemangiola** [comment]
Hello,

```r
mtcars_tidy %>% 
    heatmap(
        `Car name`, 
        Property, 
        Value,
        palette_value = circlize::colorRamp2(c(0, 1, 2, 3, 4), viridis::magma(5))
    )
```

**Comment by bishimonster** [comment]
Hello, sir,

I actually tried it before, but in this way, it simply attributed all the minus values to 0, and a huge part of the heatmap suddenly appear to be black, it may cause some biased and the plot become hard to interpret, can you let me know you follow which rule to scale the Value here.

**Comment by stemangiola** [comment]
You can `mutate` you values before hand, and setting scale="none". Without an example of your dataset it's not clear what is your issue.

**Comment by bishimonster** [comment]
dat_tidy <- dat_sub %>%
  select(-StudyID) %>%
  group_by(Visit) %>%
  summarise_all(sum, na.rm = TRUE) %>%
  pivot_longer(cols = -c(Visit), names_to='Subject', values_to='Value')

heatmap_id <- dat_tidy %>%
  heatmap(Visit, Subject, Value, cluster_rows=F,
          palette_value = circlize::colorRamp2(c(0, 1, 2, 3), viridis::magma(4))) 
 
Here is part of my code, can you tell in which step can I add the scale='none' command, I appreciate your quick response

**Comment by stemangiola** [comment]
```r
?heatmap
```

within the function heatmap

**Comment by bishimonster** [comment]
It works well, thanks man

**Comment by stemangiola** [comment]
No worries. Good luck with you research.

**Comment by asaksager** [comment]
Is it possible to use the palette_value/colorRamp2 inside e.g. add_tile in a similiar way?

For complexHeatmap the following is suggested: 
```R
library(circlize)
col_fun = colorRamp2(c(0, 5, 10), c("blue", "white", "red"))
ha = HeatmapAnnotation(foo = 1:10, col = list(foo = col_fun))

**Comment by stemangiola** [comment]
> Is it possible to use the palette_value/colorRamp2 inside e.g. add_tile in a similiar way?

it should be. Did you try to modify the README example? Can you please paste here the error?

**Comment by asaksager** [comment]
Well sorta. I tried using colorRamp2 in the 'palette' option given for add_tile, and I have tried to move the palette_value into add_tile. Like this: 

```R
library(tidyHeatmap)
library(ComplexHeatmap)
library(tidyverse)
library(circlize)


Tiny <- tibble(genes = c("Gene1","Gene1","Gene1",
                         "Gene2","Gene2","Gene2",
                         "Gene3","Gene3","Gene3"),
               type = c("Driver", "Passenger", "unkown", 
                        "Driver", "Passenger", "unkown",
                        "Driver", "Passenger", "unkown"),
               count = c(1,2,0,2,0,0,3,1,1),
               annotation = c(5,5,5,9,9,9,2,2,2))

Tiny  %>% heatmap(.row = type,  
        .column = genes, 
        .value = count) %>%  
        add_tile(annotation, palette_value = colorRamp2(c(0, 2, 5), 
                                                  c("white", "green", "red")))
```

> Error in add_tile(., annotation, palette_value = colorRamp2(c(0, 2, 5),  : 
  unused argument (palette_value = colorRamp2(c(0, 2, 5), c("white", "green", "red")))

**Comment by stemangiola** [comment]
Hello @asaksager,

please install https://github.com/stemangiola/tidyHeatmap/tree/allow_colorRamp_in_annotation branch

```r
devtools::install_github("stemangiola/tidyHeatmap@allow_colorRamp_in_annotation")
```

And Execute

```r
Tiny  %>% heatmap(.row = type,  
        .column = genes, 
        .value = count) %>%  
        add_tile(annotation, palette = colorRamp2(c(0, 2, 5), 
                                                  c("white", "green", "red")))
```

Now it is in the README too. Please stress test if you can, so we make sure it is a robust implementation.

**Comment by asaksager** [comment]
Thanks a lot for the fast update! It works very great! I have tested it on few larger datasets witout errors. 

The only thing it didn't work as 'smoothly' as for complexheatmap, is that the breaks would often be defined by a max(annotation) or min(). The best work-around I found was to pull the values and save them as variables before creating the heatmap.

**Comment by stemangiola** [comment]
Glad it worked.

Yes tidyHeatmap is integrated and does everything internally. It seems smoother on ComplexHeatmap because you already have to manipulate many variables.

If you don't care about internal breaks, but only external, you can simply provide an array of colors

```r
palette = c("white", "green", "red")

```

In this case the green will be in the middle.
