### ISSUE TITLE
How to plot nested data

### ISSUE THREAD

**Issue by VLucet** [stemangiola/tidyHeatmap#77]
Hi, I was wondering if there was a way to plot nested data. For example the following code takes your mtcars_tidy example and declines the `Value` columns into 2 different groups from the `Year` column. 

```r
mtcars_tidy <- 
    mtcars %>% 
    as_tibble(rownames="Car name") %>% 
    mutate_at(vars(-`Car name`, -hp, -vs), scale) %>%
    pivot_longer(cols = -c(`Car name`, hp, vs), names_to = "Property", values_to = "Value")
mtcars_tidy_nested <- bind_rows(mutate(mtcars_tidy, Year=1990), mutate(mtcars_tidy, Year=2000)) %>% 
  mutate(Value = runif(n = n(), min = 0, max = 10))
mtcars_tidy_nested %>% group_by(Year) %>%
    heatmap(`Car name`, Property, Value) 
```
We get the error for duplicated keys. I was wondering if there was a way to plot these (as the values in `Value` are different. 
```r
Error: Each row of output must be identified by a unique combination of keys.
Keys are shared for 576 rows:
* 403, 412
* 259, 268
* 421, 430
...
```
I would not be interested in a tree for columns, maybe just for rows (but then I would need to be nested).

**Comment by VLucet** [comment]
BTW, if you are aware of a package capable of plotting this type of data as heatmap I would also be happy to try that.

**Comment by stemangiola** [comment]
I hope I will look at this today. Recently I have been a bit overwhelmed.

**Comment by stemangiola** [comment]
I see at the moment you can do 

```r
mtcars_tidy_nested %>% unite( "Car name", c(`Car name`, Year), remove = F) %>%  group_by(Year) %>% 
    heatmap(`Car name`, Property, Value) 
```

**Comment by VLucet** [comment]
Thanks! This certainly works, but of course the labels on the right remain problematic. This can be fixed as long as one doesn't want clustering and is willing to provide custom `row_labels`.

**Comment by stemangiola** [comment]
New feature request has been created 

https://github.com/stemangiola/tidyHeatmap/issues/79
