### ISSUE TITLE
Is it possible to add labels to the variable names in a correlation plot?

### ISSUE THREAD

**Issue by lorenzoFabbri** [stemangiola/tidyHeatmap#78]
I need to plot a correlation matrix and to add the labels of the variables (added with the R package `labelled`) to it. For instance, group together all the variables belonging to the same group. I was not able to find an example for a correlation matrix, but the idea is to get something similar to [this](https://stackoverflow.com/questions/17860120/drawing-heatmap-with-dendrogram-along-with-sample-labels), which is an heatmap where the variables where colored according to another column of the dataframe.

Is this possible with `tidyHeatmap`?

**Comment by stemangiola** [comment]
Would add_tile not do the job?

To colour the dendrogram you have to use ComplexHeatmap options, which you can inject into the heatmap() function.

Please let me know if you solve this, and we can add your example in the README.

**Comment by lorenzoFabbri** [comment]
@stemangiola Sorry, I did not receive a notification for your message. I can try right now and I'll let you know.

**Comment by stemangiola** [comment]
Closing this, feel free to reopen it.
