### ISSUE TITLE
Default value of `.scale`

### ISSUE THREAD

**Issue by grst** [stemangiola/tidyHeatmap#80]
Personally, I found it really confusing that tidyheatmap automatically scales data per row. 

It's nice to have this functionality, but how about setting the default to "none"?

**Comment by stemangiola** [comment]
Yes, sometimes I think the same. What do other heatmap software do? I have the feeling that scaling colors by row is kind of the default.

**Comment by grst** [comment]
I have been using `pheatmap` (default scale="none") and `complexHeatmap`
(which doesn't support scaling at all) before.

**Comment by stemangiola** [comment]
Hello,

I did not forget, this. I am just thinking about the best way (in case I decide to drop the default) to communicate the transition, as users would get two different plots for different versions of the software.

**Comment by grst** [comment]
If you are adhering to Semantic Versioning, this would probably require bumping the major version number to `2.0`...

In any case adding a note to the changelog and maybe a `message()` upon package load is probably good practice :)

**Comment by morriso1** [comment]
Hi, I would like to second this. I was surprised when additional scaling was performed upon plotting.

Thank you for developing tidyHeatmap. It is a super useful tool!

**Comment by stemangiola** [comment]
Thanks for the feedback. I have created a pull request. Please try to install the branch and if you can give feedback.

Thanks
