### ISSUE TITLE
Error loading tidyHeatmap package within Snakemake

### ISSUE THREAD

**Issue by marcora** [stemangiola/tidyHeatmap#9]
I am loading tidyHeatmap (together with many others) within an R script launched by Snakemake and I get this error:

Error: package or namespace load failed for ‘tidyHeatmap’:
 object ‘is_present’ is not exported by 'namespace:lifecycle'
Execution halted

I never got this error when loading any other package and the same error appears when just loading tidyHeatmap in isolation. No problem when loading tidyHeatmap from an interactive R session.

**Comment by stemangiola** [comment]
Is it possible that an older version of lifecycle is present in your system < 0.2.0? I should add versions in my DESCRIPTION

**Comment by stemangiola** [comment]
Hello, I close for inactivity. Reopen if needed.
